FROM python:3.9-slim

WORKDIR /app

# Install minimal producer dependency
RUN pip install --no-cache-dir kafka-python

# Copy application files and dataset
COPY producer_simulator.py config.ini ./
COPY data/ ./data/

ENV PYTHONUNBUFFERED=1
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:29092
ENV KAFKA_TOPIC=retail_stream
ENV CSV_FILEPATH=./data/OnlineRetail.csv

CMD ["python3", "producer_simulator.py"]
